/** A complete, valid set of form values, used as the base for tests and clearly-labelled demo data. */
export const SAMPLE_VALUES: Record<string, unknown> = {
  firstName: "Amina", middleName: "", lastName: "Bello", gender: "FEMALE", dateOfBirth: "1998-04-12",
  phone: "0803 000 0000", whatsapp: "", email: "Amina.Bello@example.com", nationality: "Nigerian",
  state: "Kaduna", lga: "Zaria", community: "Samaru", address: "12 Farm Road, Samaru", residenceSetting: "RURAL",
  languages: ["English", "Hausa"], languagesOther: "", disability: "NO", disabilityType: "", accessibilityNeeds: "",
  businessName: "Green Harvest Aggregation", registrationStatus: "NOT_REGISTERED", registrationNumber: "",
  businessStage: "GROWING", yearStarted: "2022", businessState: "Kaduna", businessLga: "Zaria", businessAddress: "Plot 4, Zaria market",
  businessSetting: "RURAL", website: "", socialHandles: "@greenharvest", valueChain: "MAIZE", valueChainOther: "",
  applicantRole: "FOUNDER", applicantRoleOther: "",
  description: "We aggregate and dry maize from smallholders and sell to feed millers.",
  problem: "Smallholder maize farmers lose income through poor drying and no reliable buyers.",
  solution: "Solar dryers and a guaranteed offtake arrangement that raises farmer prices.",
  originality: "We combine drying, storage and buying in one village-level hub.",
  innovation: "Pay-on-delivery mobile wallet payments for farmers with digital records.",
  mainCustomers: "Feed millers and poultry farms", targetMarket: "Northern Nigeria feed industry",
  customersServed: "14", generatesRevenue: "YES", revenueRange: "5M_20M", revenueSource: "Maize sales",
  fullTime: "4", partTime: "6", youthEmployed: "7", womenEmployed: "5",
  farmersReached: "320", jobsCreated: "10", womenReached: "140", youthReached: "90", communitiesReached: "8",
  socialImpact: "Farmers in 8 villages increased maize income by roughly 22% after using our hub.",
  beneficiaries: "Smallholder maize farmers, mostly women and youth", peopleBenefited: "320",
  agriImpactAreas: ["POST_HARVEST", "MARKET_ACCESS"], environmentalImpact: "Post-harvest losses cut from about 25% to 8%.",
  supportNeeds: ["FINANCE", "MENTORSHIP"], supportNeedsOther: "", programmeGoal: "Secure seed capital to add two more drying hubs.",
  docPitchDeck: "", docBusiness: "", docRegistration: "", docImages: "", docEvidence: "",
};
