/**
 * Generates apps-script/Code.gs from the app's own sheet definitions, so the script's headers can never drift from the code.
 * Usage: npm run build:appsscript
 */
import { writeFileSync } from "node:fs";
import { HEADERS } from "../lib/google-sheets/schema";

const tabs = Object.fromEntries(Object.entries(HEADERS).map(([k, v]) => [k, [...v]]));
const code = `/**
 * AGRA–SMEDAN Youth Agri-Innovation Contest: data service that lives INSIDE the Google Sheet.
 * (Generated by "npm run build:appsscript". Do not edit the TABS list by hand.)
 *
 * SETUP (once):
 *   1. In the sheet: Extensions > Apps Script. Paste this whole file over the default code. Save.
 *   2. Project Settings (gear icon) > Script properties > Add property:  SECRET = a long random text (32+ characters).
 *   3. Select the function "setup" in the toolbar > Run. Approve the permissions. (Creates the tabs + header row.)
 *   4. Deploy > New deployment > type "Web app":  Execute as = Me,  Who has access = Anyone.  Copy the Web app URL.
 *   5. Put the URL in APPS_SCRIPT_URL and the same secret in APPS_SCRIPT_SECRET on the website.
 * If you change this code later: Deploy > Manage deployments > Edit > New version > Deploy.
 */
var TABS = ${JSON.stringify(tabs, null, 2)};

function setup() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  Object.keys(TABS).forEach(function (name) {
    var sheet = ss.getSheetByName(name) || ss.insertSheet(name);
    var headers = TABS[name];
    var range = sheet.getRange(1, 1, 1, headers.length);
    range.setNumberFormat('@');           // plain text: stops Sheets turning dates, phone numbers or "=..." into other things
    range.setValues([headers]);
    range.setFontWeight('bold');
    sheet.setFrozenRows(1);
  });
  var blank = ss.getSheetByName('Sheet1');
  if (blank && blank.getLastRow() === 0 && ss.getSheets().length > 1) ss.deleteSheet(blank);
}

function doGet() { return reply({ ok: true, service: 'agra-smedan-contest' }); }   // health check only, never returns data

function doPost(e) {
  var lock = LockService.getScriptLock();
  lock.waitLock(25000);                    // one write at a time, so two applicants never overwrite each other
  try {
    var req = JSON.parse(e.postData.contents);
    var secret = PropertiesService.getScriptProperties().getProperty('SECRET');
    if (!secret || req.secret !== secret) return reply({ error: 'forbidden' });
    if (!Object.prototype.hasOwnProperty.call(TABS, req.sheet)) return reply({ error: 'unknown sheet' });
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(req.sheet);
    if (!sheet) return reply({ error: 'sheet missing: run setup()' });

    switch (req.action) {
      case 'read': {
        if (sheet.getLastRow() === 0) return reply({ rows: [] });
        return reply({ rows: sheet.getDataRange().getDisplayValues() });
      }
      case 'append': {
        var row = cleanRow(req.row);
        var r = Math.max(sheet.getLastRow(), 1) + 1;
        writeRow(sheet, r, row);
        return reply({ ok: true, rowNumber: r });
      }
      case 'updateRow': {
        var n = Number(req.rowNumber);
        if (!(n >= 2) || n % 1 !== 0) return reply({ error: 'bad row number' });   // never touch the header row
        writeRow(sheet, n, cleanRow(req.row));
        return reply({ ok: true });
      }
      case 'clearRow': {
        var c = Number(req.rowNumber), w = Math.min(Number(req.width) || 1, 200);
        if (!(c >= 2) || c % 1 !== 0) return reply({ error: 'bad row number' });
        sheet.getRange(c, 1, 1, w).clearContent();
        return reply({ ok: true });
      }
      default: return reply({ error: 'unknown action' });
    }
  } catch (err) {
    return reply({ error: String(err && err.message ? err.message : err) });
  } finally {
    lock.releaseLock();
  }
}

function cleanRow(row) {
  if (!Array.isArray(row) || row.length === 0 || row.length > 200) throw new Error('bad row');
  return row.map(function (v) { return v == null ? '' : String(v).slice(0, 45000); });
}
function writeRow(sheet, rowNumber, row) {
  var range = sheet.getRange(rowNumber, 1, 1, row.length);
  range.setNumberFormat('@');             // store exactly what the website sent
  range.setValues([row]);
}
function reply(obj) { return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON); }
`;
writeFileSync("apps-script/Code.gs", code);
console.log(`apps-script/Code.gs written (${Object.keys(tabs).length} tabs)`);
